### ISSUE TITLE
Capacity reserve margin constraint documentation missing H2 sector terms

### ISSUE THREAD

**Issue by dharik13** [macroenergy/Dolphyn.jl#147]
Documentation for capacity reserve margin constraint missing terms related to electricity use by other sectors (e.g. H2). Need to be updated.

**Comment by RuaridhMacd** [comment]
- [ ] @RuaridhMacd Check if @Junwenlaw has done this. The model includes the terms but the documentation does not.

**Comment by Junwenlaw** [comment]
Model include the terms for capacity reserve margin for H2 electrolyzer and storage
