### ISSUE TITLE
[BUG]Can't run the example of "ERCOT_1stg_hourly_5GW_base_tmr"

### ISSUE THREAD

**Issue by Camyucan** [macroenergy/Dolphyn.jl#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run this example, the progress is stuck in this line:

`EP = generate_model(mysetup, myinputs, OPTIMIZER)`

The error output is:
`1-element ExceptionStack:
LoadError: MathOptInterface.SetAttributeNotAllowed{MathOptInterface.RawOptimizerAttribute}: Setting attribute MathOptInterface.RawOptimizerAttribute("run_crossover") cannot be performed:

Invalid value `false::Bool` for option "run_crossover", expected a value of type `String`.

 You may want to use a `CachingOptimizer` in `AUTOMATIC` mode or you may need to call `reset_optimizer` before doing this operation if the `CachingOptimizer` is in `MANUAL` mode.
Stacktrace:
  [1] set(model::HiGHS.Optimizer, param::MathOptInterface.RawOptimizerAttribute, value::Bool)
    @ HiGHS C:\Users\qw\.julia\packages\HiGHS\y7dA4\src\MOI_wrapper.jl:524
  [2] _instantiate_and_check(optimizer_constructor::MathOptInterface.OptimizerWithAttributes)
    @ MathOptInterface C:\Users\qw\.julia\packages\MathOptInterface\2rAFb\src\instantiate.jl:120
  [3] instantiate(optimizer_constructor::Any; with_bridge_type::Type{Float64}, with_cache_type::Nothing)
    @ MathOptInterface C:\Users\qw\.julia\packages\MathOptInterface\2rAFb\src\instantiate.jl:175
  [4] set_optimizer(model::JuMP.Model, optimizer_constructor::Any; add_bridges::Bool)
    @ JuMP C:\Users\qw\.julia\packages\JuMP\Y2NoH\src\optimizer_interface.jl:365
  [5] set_optimizer
    @ C:\Users\qw\.julia\packages\JuMP\Y2NoH\src\optimizer_interface.jl:358 [inlined]
  [6] #_#1
    @ C:\Users\qw\.julia\packages\JuMP\Y2NoH\src\JuMP.jl:182 [inlined]
  [7] GenericModel
    @ C:\Users\qw\.julia\packages\JuMP\Y2NoH\src\JuMP.jl:174 [inlined]
  [8] generate_model(setup::Dict{Any, Any}, inputs::Dict{Any, Any}, OPTIMIZER::MathOptInterface.OptimizerWithAttributes, modeloutput::Nothing)
    @ Dolphyn C:\Users\qw\.julia\packages\Dolphyn\QyHqs\src\generate_model.jl:99
  [9] generate_model(setup::Dict{Any, Any}, inputs::Dict{Any, Any}, OPTIMIZER::MathOptInterface.OptimizerWithAttributes)
    @ Dolphyn C:\Users\qw\.julia\packages\Dolphyn\QyHqs\src\generate_model.jl:92
 [10] top-level scope
    @ C:\Users\qw\DOLPHYN\Example_Systems\ERCOT_1stg_hourly_5GW_base_tmr\Run.jl:82
 [11] include(fname::String)
    @ Base.MainInclude .\client.jl:489
 [12] top-level scope
    @ REPL[11]:1
in expression starting at C:\Users\qw\DOLPHYN\Example_Systems\ERCOT_1stg_hourly_5GW_base_tmr\Run.jl:82`

It seems like a bug about the optimizer.
Do you know how to solve it? Thanks :)

### Environment

```markdown
- OS:
- Julia version:
- Solver:
- Solver version:
```

**Comment by RuaridhMacd** [comment]
Hi @Camyucan Thanks for this. I've just created a PR which should address the issue. We're testing it and it should be merged shortly. Feel free to try the [clean-up-examples](https://github.com/macroenergy/Dolphyn.jl/tree/clean-up-examples) branch in the meantime if you need to work on it today.

**Comment by RuaridhMacd** [comment]
@Camyucan The changes have been merged - let me know if you still have the issue
